import os

CLOBBER_ROOT = os.path.dirname(__file__)
PROJECT_ROOT = os.path.join(CLOBBER_ROOT, f'..{os.path.sep}..')
CLOBBER_DATA = os.path.join(PROJECT_ROOT, f'hpg_construction{os.path.sep}outputs')

WINDOW_PREDEFINED_PROPERTIES = [
    'closed',
    'console',
    'defaultStatus',
    'document',
    'frameElement',
    'frames',
    'history',
    'innerHeight',
    'innerWidth',
    'length',
    'localStorage',
    'location',
    'name',
    'navigator',
    'opener',
    'outerHeight',
    'outerWidth',
    'pageXOffset',
    'pageYOffset',
    'parent',
    'screen',
    'screenLeft',
    'screenTop',
    'screenX',
    'screenY',
    'sessionStorage',
    'scrollX',
    'scrollY',
    'self',
    'status',
    'top',
    'alert',
    'atob',
    'blur',
    'btoa',
    'clearInterval',
    'clearTimeout',
    'close',
    'confirm',
    'focus',
    'getComputedStyle',
    'getSelection',
    'matchMedia',
    'moveBy',
    'moveTo',
    'open',
    'print',
    'prompt',
    'requestAnimationFrame',
    'resizeBy',
    'resizeTo',
    'setInterval',
    'setTimeout',
    'stop'
]